### ISSUE TITLE
spark/databricks compatibility

### ISSUE THREAD

**Issue by fivetran-jamie** [fivetran/dbt_facebook_ads_creative_history#6]
currently no models will run if the target warehouse is not bq/redshift/snowflake. how much of a lift would incorporating databricks be?

**Comment by kristin-bagnall** [comment]
@DylanBaker is currently working on implementing

**Comment by fivetran-joemarkiewicz** [comment]
Closing this issue as `v0.2.2` incorporates Databricks compatibility.
